language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO_VERSION="Django<2.2" DB=sqlite
  - DJANGO_VERSION="Django<3" DB=sqlite
  - DJANGO_VERSION="Django<3.1" DB=sqlite
install:
  - pip install -q "${DJANGO_VERSION}"
  - pip install coveralls coverage django-discover-runner
script:
  - coverage run --rcfile=.coveragerc setup.py test
after_success:
  - coveralls
